# Generated by Django 5.2.7 on 2025-10-26 16:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gmail', models.EmailField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
