# Generated by Django 5.2.7 on 2025-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
