# Generated by Django 5.2.7 on 2025-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
